import type { Metadata } from "next";
import "./globals.css";
import { AvanGarde, ProximaNova } from "@/lib/customFonts";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar";
import ResumeDownloadSpinner from "@/components/resume-download-spinner";

export const metadata: Metadata = {
  title: "Pratik's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className={cn(AvanGarde.variable, ProximaNova.variable)}>
        <Navbar />
        {children}
        <ResumeDownloadSpinner />
      </body>
    </html>
  );
}
